# application.yml
spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# JWT
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000 # 24h
  refresh-token:
    expiration: 604800000 # 7d

# Logging
logging:
  level:
    com.payment.system: DEBUG
    org.springframework.security: DEBUG